name: ci

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always

      # sccache
      RUSTC_WRAPPER: sccache
      SCCACHE_GHA_ENABLED: "true"

      SCCACHE_LOG: debug
      SCCACHE_NO_DAEMON: 1

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Install sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: CI (xtask)
        run: cargo ci

      - name: sccache stats
        run: sccache --show-stats
